### ISSUE TITLE
I want to use llvm,but I can't find_package(LLVM REQUIRED CONFIG)!

### ISSUE THREAD

**Issue by harrisonGPU** [tsnl/pdm#1]
Hello tsnl,I see you meet same problem about LLVM on Windows!
Let me tell you some retails：
First，I git clone llvm-project. The path is `D:\llvm-project`
And then :
`cd llvm-project`
`mkdir build`
`cd build`
`cmake -G "Visual Studio 16 2019" ../llvm`
`cmake --build . --target install`
Do above these commands,I build my project.The path is `D:\kaleodoscope`,and then:
`cd kaleodoscope`
`mkdir build`
`cd build`
`cmake ..`
it will be error!
this is  
[CMakeOutput.log](https://github.com/tsnl/pdm/files/9784182/CMakeOutput.log)
```
Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.19044.
-- The C compiler identification is MSVC 19.29.30146.0
-- The CXX compiler identification is MSVC 19.29.30146.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:10 (find_package):
  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
```

**Comment by harrisonGPU** [comment]
this is [project](https://github.com/ejunjsh/kaleidoscope)

**Comment by tsnl** [comment]
Hi @TSWorld1314,

I saw your comment on [another issue](https://github.com/microsoft/vcpkg/issues/15448) I opened with VCPkg some years back. Thus, I'm going to assume you have installed LLVM with VCPkg.

As you can see on the other thread, the fix was two-fold:
- when installing LLVM with VCPkg, ensure you specify the 64-bit version by using the `llvm:x64-windows` package instead of just `llvm`, which defaults to `llvm:x86-windows`. 
- when configuring with CMake on Windows, specify the `-A x64` flag to use the 64-bit compilation toolchain. If you use Visual Studio Code and the 'CMake Tools' extension, VSCode will help you configure this setting as long as you select a 64-bit compiler. According to your logs, you are already running with 64-bit windows, so **this step should not be needed for you.**

Good luck on your compiler endeavors!

P.S. please consider using a website like StackOverflow next time. When you create a GitHub issue on a repo, it indicates there is something wrong with the repo's code. I think such questions would be a better fit for StackOverflow, where those who answer would be rewarded by positive ratings. Try to save GitHub issues for bugs/feature suggestions/etc. specific to the repo so you are not dismissed by project maintainers for diverting their time to non-issues.

**Comment by harrisonGPU** [comment]
> 

Thanks a lot！
